name: pablodraw # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '3.2.1-30610' # just for humans, typically '1.2+git' or '1.3.2'
summary: PabloDraw - the ANSI drawing app
description: |
  PabloDraw - the ANSI drawing app

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
icon:  pablodraw_icon.png
title: PabloDraw

apps:
  pablodraw:
    command: PabloDraw
parts:
  pablodraw:
    # See 'snapcraft plugins'
    plugin: dump
    source: .
#    build-packages: [default-jre]
#    stage-packages: [default-jre]
    organize:
      pablodraw: build/
      pablodraw.1: man/man1/

architectures:
  - build-on: amd64

